#!/bin/bash
# Update and install 

sudo apt-get update -y
sudo apt-get install -y apache2

# Remove the default file created by Ubuntu's installation
if [ -f /var/www/html/index.html ]; then
    sudo rm -f /var/www/html/index.html
fi
